import streamlit as st
from PIL import Image
import json
import os

from predict import ensemble_predict
from db import save_prediction


# ---------------- Page Configuration ----------------
st.set_page_config(
    page_title="AI Skin Disease Detection",
    page_icon="🩺",
    layout="centered"
)

# ---------------- Title ----------------
st.title("AI-Based Skin Disease Detection System")

st.markdown(
    "Upload a skin image to obtain an **ensemble-based AI prediction** "
    "along with confidence and medical guidance."
)

# ---------------- Medical Disclaimer ----------------
st.warning(
    "⚠ **Medical Disclaimer**\n\n"
    "This application is developed strictly for **academic and research purposes**. "
    "It is **NOT a medical diagnosis system**. The predictions generated by this system "
    "should not be considered as professional medical advice. "
    "Always consult a certified dermatologist or healthcare professional."
)

# ---------------- Load Disease → Doctor Mapping ----------------
@st.cache_data
def load_doctor_map():
    with open(
    os.path.join(os.path.dirname(__file__), "doctor_map.json"), "r"
) as f:
        return json.load(f)

doctor_map = load_doctor_map()

# ---------------- Image Upload ----------------
uploaded_file = st.file_uploader(
    "Upload a skin image (JPG / PNG / JPEG)",
    type=["jpg", "jpeg", "png"]
)

# ---------------- Display Image ----------------
if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_container_width=True)

    # ---------------- Prediction Button ----------------
    if st.button("Analyze Image"):
        with st.spinner("Running ensemble prediction..."):
            label, confidence, top_probs = ensemble_predict(image)

        # ---------------- Prediction Output ----------------
        st.success("Prediction completed successfully")

        st.markdown(f"### 🦠 Predicted Disease: **{label}**")
        st.markdown(f"### 📊 Confidence: **{confidence:.2f}%**")

        # ---------------- Low Confidence Warning ----------------
        if confidence < 60:
            st.warning(
                "⚠ **Low Confidence Prediction**\n\n"
                "The model is not highly confident in this prediction. "
                "Please consult a dermatologist for accurate diagnosis."
            )

        # ---------------- Doctor Recommendation ----------------
        recommended_doctor = doctor_map.get(label, "General Physician")

        st.markdown(
            f"### 👨‍⚕️ Recommended Specialist: **{recommended_doctor}**"
        )

        # ---------------- Top Probabilities ----------------
        st.markdown("### 🔍 Top Prediction Probabilities")

        for disease, prob in sorted(
            top_probs.items(),
            key=lambda x: x[1],
            reverse=True
        ):
            st.write(f"- **{disease}**: {prob * 100:.2f}%")

        # ---------------- Save History ----------------
        save_prediction(
            disease=label,
            confidence=confidence
        )

        st.info("Prediction saved successfully.")

# ---------------- Footer ----------------
st.markdown("---")
st.caption("AI Skin Disease Detection System | Academic Project")
